languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "Johanna M. Christoph"
# logo = "img/.png"
description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
  name = "Johanna M. Christoph"
  image = "img/avata.png"
  headline = "Welcome to my personal website"
  bio = "Computer Science Student & Entrepreneur"
   links = [
     { github = "https://github.com/Jojo-M-C" },
     { linkedin = "https://www.linkedin.com/in/johanna-m-christoph-039b94177/" },
     { instagram = "https://www.instagram.com/jojo_m_chr/" }
   ]
